.TH DHCP-STATS 1
.SH NAME
dhcp-stats \- diplay statistics about DHCP traffic
.SH SYNOPSIS
.B dhcp-stats
[\fB\-n\fR \fIFILENAME\fR]
[\fB\-i\fR \fIINTERFACE-NAME\fR]
\fIip-prefix\fR [ \fIip-prefix\fR [ ... ] ]
.SH DESCRIPTION
Dlhší text aaaaa.

Dlhší text bbbbb.
.SH OPTIONS
.TP
\fB\-r\fR=\fIFILENAME\fR
read packets from pcap file
.TP
\fB\-i\fR=\fIINTERFACE-NAME\fR
capture packets from network interface
.TP
.BR \-h ", " \-\-help
display help and exit
.TP
.BR \-\-version
output version information and exit
.SH AUTHOR
.TP
Written by Marián Tarageľ (xtarag01).