.TH DHCP-STATS 1
.SH NAME
dhcp-stats \- diplay statistics about the IP prefix utilization
.SH SYNOPSIS
.B dhcp-stats
[\fB\-n\fR \fIFILENAME\fR]
[\fB\-i\fR \fIINTERFACE-NAME\fR]
\fIip-prefix\fR [ \fIip-prefix\fR [ ... ] ]
.SH DESCRIPTION
The program will monitor DHCP traffic and show stats about IP prefix utilization. When the IP prefix exceeds 50 % of the allocated IP addressed, the program will notify the administrator through syslog. The program can generate stats from a pcap file. It can also listen on a network interface.
.SH OPTIONS
.TP
\fB\-r\fR=\fIFILENAME\fR
Read packets from pcap file (.pcap or .pcapng). Pcap file must exists. This option can not be combined with -i, but at least one must be present.
.TP
\fB\-i\fR=\fIINTERFACE-NAME\fR
Capture packets from network interface. Network interface must exists. This option can not be combined with -r, but at least one must be present.
.TP
\fIip-prefix\f
Net range for which stats will be generated in format x.x.x.x/y, where x.x.x.x is valid IP address, and y is a length of network prefix (0 - 32). Program can work with multiple IP prefixes. They can also overlap. If the user will enter IP prefix that is not valid, for example 192.168.1.15/24, that the IP adress will be masked based on the subnet mask length to 192.168.1.0/24. Program will use this IP adress instead for checking wheteher the IP address is in the subnet. But in the final output, original IP address will be printed.
.TP
.BR \-h ", " \-\-help
display help and exit
.TP
.BR \-\-version
output version information and exit
.SH AUTHOR
.TP
Written by Marián Tarageľ (xtarag01).
