.TH DHCP-STATS 1
.SH NAME
dhcp-stats \- diplay statistics about DHCP traffic
.SH SYNOPSIS
.B dhcp-stats
[\fB\-n\fR \fIFILENAME\fR]
[\fB\-i\fR \fIINTERFACE-NAME\fR]
\fIip-prefix\fR [ \fIip-prefix\fR [ ... ] ]
.SH DESCRIPTION
The program will monitor DHCP traffic and show stats about IP prefix utilization. When the IP prefix exceeds 50 % of the allocated IP addressed, the program will notify the administrator through syslog. The program can generate stats from a pcap file. It can also listen on a network interface.
.SH OPTIONS
.TP
\fB\-r\fR=\fIFILENAME\fR
read packets from pcap file
.TP
\fB\-i\fR=\fIINTERFACE-NAME\fR
capture packets from network interface
.TP
\fIip-prefix\f
net range for which stats will be generated in format x.x.x.x/y, where x.x.x.x is valid IP address, and y is a length of network prefix
.TP
.BR \-h ", " \-\-help
display help and exit
.TP
.BR \-\-version
output version information and exit
.SH AUTHOR
.TP
Written by Marián Tarageľ (xtarag01).